//! GENERATED by tools/extract_constants.py from playgroundz.elf - do not edit.
//! ELF SHA-256: 5cef3efc7005fb71fed0a75e60ee240ee6ac4243b00dd3296e6e53ca269a3e2c
#![allow(dead_code)]

/// LocalCharacterControl::Update turn step (analog, normal) - `gTurnRate` @ 0x805fec58
pub const TURN_RATE: f32 = 1.0;
/// LocalCharacterControl::Update turn step (analog, large heading error) - `gTurnRateFast` @ 0x805fec5c
pub const TURN_RATE_FAST: f32 = 2.0;
/// LocalCharacterControl::Update turn step (digital/dpad input) - `gTurnRateDigital` @ 0x805fec60
pub const TURN_RATE_DIGITAL: f32 = 0.10000000149011612;
/// idle time (ms) before movement becomes camera-absolute again - `gLocalCharacterControlStopTimeBeforeAbsoluteMovement` @ 0x805fec64
pub const STOP_TIME_BEFORE_ABSOLUTE_MOVEMENT_MS: i32 = 100;
/// dpad-to-analog smoothing ramp time (ms) - `gDigitalTransitionTime` @ 0x805fec68
pub const DIGITAL_TRANSITION_TIME_MS: i32 = 150;
/// orbit camera distance - `gOrbitCameraDistance` @ 0x805ffa50
pub const ORBIT_CAMERA_DISTANCE: f32 = 20.0;
/// orbit camera height - `gOrbitCameraHeight` @ 0x805ffa54
pub const ORBIT_CAMERA_HEIGHT: f32 = 3.799999952316284;
/// hinge camera distance - `gHingeCameraDistance` @ 0x805ffa30
pub const HINGE_CAMERA_DISTANCE: f32 = 3.5999999046325684;
/// hinge camera far distance - `gHingeCameraDistanceFar` @ 0x805ffa34
pub const HINGE_CAMERA_DISTANCE_FAR: f32 = 3.799999952316284;
/// frame camera distance - `gFrameCameraDistance` @ 0x805ffa18
pub const FRAME_CAMERA_DISTANCE: f32 = 2.9000000953674316;
/// frame camera height - `gFrameCameraHeight` @ 0x805ffa20
pub const FRAME_CAMERA_HEIGHT: f32 = 1.100000023841858;
/// camera speed cap - `gCameraSpeedCap` @ 0x805ffa68
pub const CAMERA_SPEED_CAP: f32 = 2.0;
/// camera transition speed - `gTransitionSpeed` @ 0x805ffa48
pub const CAMERA_TRANSITION_SPEED: f32 = 1.0;
/// CharacterState default at +0x10 - `__ct__14CharacterStateFv+field 0x10` @ 0x802edf8c
pub const STATE_FIELD_10: f32 = 0.25;
/// CharacterState default at +0x14 - `__ct__14CharacterStateFv+field 0x14` @ 0x802edf8c
pub const STATE_FIELD_14: f32 = 0.8999999761581421;
/// CharacterState default at +0x18 - `__ct__14CharacterStateFv+field 0x18` @ 0x802edf8c
pub const STATE_MAX_SPEED: f32 = 5.0;
/// CharacterState default at +0x1c - `__ct__14CharacterStateFv+field 0x1c` @ 0x802edf8c
pub const STATE_FIELD_1C: f32 = 2.5;
/// CharacterState default at +0x20 - `__ct__14CharacterStateFv+field 0x20` @ 0x802edf8c
pub const STATE_FIELD_20: f32 = 4.0;
/// CharacterState default at +0x24 - `__ct__14CharacterStateFv+field 0x24` @ 0x802edf8c
pub const STATE_FIELD_24: f32 = 1.0;
/// LocalCharacterControl::Update: |axis| must exceed this (0x802ef1fc) - `.sdata2@0x80605834` @ 0x80605834
pub const STICK_DEAD_ZONE: f32 = 0.10000000149011612;
/// pi used by Update - `.sdata2@0x8060583c` @ 0x8060583c
pub const PI: f32 = 3.1415927410125732;
/// 180.0 used to convert camera yaw - `.sdata2@0x80605840` @ 0x80605840
pub const DEG_PER_PI: f32 = 180.0;
pub const ELF_SHA256: &str = "5cef3efc7005fb71fed0a75e60ee240ee6ac4243b00dd3296e6e53ca269a3e2c";
