//! On2 VP6 video decoder for the EA `MVhd` movies (`video/*/*.vp6`).
//!
//! The game links On2's VP6 decoder (`VP6_LoadFrame` 0x802a289c, `VP6_DecodeFrameMbs` 0x802a08fc,
//! `VP6_PredictFilteredBlock` 0x8029bc54, ...); every constant table used here is copied from it
//! (`vp6_tables.rs`, generated by tools/extract_vp6_tables.py).  The bitstream procedures follow that decoder:
//! * header (`VP6_LoadFrame`): frame type, 6-bit quantizer, multi-stream flag; key frames add version (5 bits), profile
//!   (2 bits), interlace flag, the second-partition offset, and macroblock rows/columns through the bool decoder;
//! * profile 0 (all movies here) never reads filter or loop-filter fields, and `VP6_PredictFilteredBlock` then uses the
//!   bilinear predictor without the in-loop deblock copy;
//! * macroblock-type deltas (`VP6_decodeModeDiff`: 205, 171, 83, 199, 140, 125, 104 and 4 x 7 bits);
//! * coefficient tokens, DC prediction, the VP3/VP6 integer IDCT (DC-only add `(dc + 15) >> 5`).
//! The picture is coded bottom-up; frames are returned top-down.
use crate::vp6_tables as t;

// ---------------------------------------------------------------------------------------------------------------
// Bool decoder, as linked into the game: `VP6_StartDecode` (0x8029cccc) loads a 32-bit value, range 255, count 8;
// `VP6_DecodeBool` (0x8029a6fc) renormalises while range < 128; `VP6_DecodeBool128` (0x8029a794) always shifts once
// (its range can reach 256).  Literal fields (`VP6_bitread`), sign bits and 4MV block types use the latter.
struct Rac<'a>{d:&'a [u8],pos:usize,range:u32,value:u32,count:i32}
impl<'a> Rac<'a>{
    fn new(d:&'a [u8])->Self{
        let b=|i:usize|*d.get(i).unwrap_or(&0) as u32;
        Rac{d,pos:4,range:255,value:(b(0)<<24)|(b(1)<<16)|(b(2)<<8)|b(3),count:8}
    }
    #[inline] fn shift(&mut self){
        self.range<<=1;self.value<<=1;self.count-=1;
        if self.count==0{self.value|=*self.d.get(self.pos).unwrap_or(&0) as u32;self.pos+=1;self.count=8}
    }
    #[inline] fn prob(&mut self,p:u8)->bool{
        let split=1+(((self.range-1)*p as u32)>>8);let big=split<<24;
        let bit=self.value>=big;if bit{self.range-=split;self.value-=big}else{self.range=split}
        while self.range<128{self.shift()}
        bit
    }
    #[inline] fn bit128(&mut self)->bool{
        let split=(self.range+1)>>1;let big=split<<24;
        let bit=self.value>=big;if bit{self.range-=split;self.value-=big}else{self.range=split}
        self.shift();bit
    }
    /// `VP6_bitread`: MSB-first literal through `DecodeBool128`.
    fn gets(&mut self,n:u32)->i32{(0..n).fold(0,|v,_|(v<<1)|self.bit128() as i32)}
    fn gets_nn(&mut self,n:u32)->u8{let v=self.gets(n)<<1;(v+(v==0) as i32) as u8}
    fn tree(&mut self,tree:&[(i32,usize)],probs:&[u8])->i32{
        let mut i=0;
        while tree[i].0>0{if self.prob(probs[tree[i].1]){i+=tree[i].0 as usize}else{i+=1}}
        -tree[i].0
    }
}

/// MSB-first bit reader over the coefficient partition (Huffman mode).
struct Bits<'a>{d:&'a [u8],pos:usize}
impl<'a> Bits<'a>{
    fn bit(&mut self)->Result<u32,String>{let b=*self.d.get(self.pos>>3).ok_or("Huffman coefficient data exhausted")?;let v=(b>>(7-(self.pos&7)))&1;self.pos+=1;Ok(v as u32)}
    fn get(&mut self,n:u32)->Result<u32,String>{let mut v=0;for _ in 0..n{v=(v<<1)|self.bit()?}Ok(v)}
}
/// Huffman code built from a bool-tree model (`VP6_BuildHuffTree` 0x802a34ac / `ConvertBoolTrees` 0x8029fb3c):
/// leaf frequencies are the probabilities propagated down the tree (256 at the root, `count*p>>8`, zero -> 1), then
/// a Huffman tree is built over them (ascending count, ties by descending symbol, merged nodes placed before equal counts).
#[derive(Clone,Default)] struct Huff{nodes:Vec<(i64,i32,usize)>,root:usize}
const HNODE:i32=-1;
impl Huff{
    fn build(model:&[u8],map:&[usize],size:usize)->Huff{
        let mut count=vec![0i64;2*size];count[size]=256;
        for i in 0..size-1{
            let c=count[size+i];let a=c*model[i] as i64>>8;let b=c*(255-model[i] as i64)>>8;
            count[map[2*i]]=a+(a==0) as i64;count[map[2*i+1]]=b+(b==0) as i64;
        }
        // (count, symbol, first child)
        let mut nodes:Vec<(i64,i32,usize)>=(0..size).map(|i|(count[i],i as i32,0)).collect();
        nodes.sort_by(|a,b|((a.0-b.0)*16+(b.1-a.1) as i64).cmp(&0));
        nodes.resize(2*size,(0,0,0));
        let mut cur=size;
        let mut i=0;
        while i<size*2-2{
            let c=nodes[i].0+nodes[i+1].0;
            let mut j=cur;
            while j>i+2{if c>nodes[j-1].0{break}nodes[j]=nodes[j-1];j-=1}
            nodes[j]=(c,HNODE,i);cur+=1;i+=2;
        }
        Huff{nodes,root:size*2-2}
    }
    fn read(&self,b:&mut Bits)->Result<i32,String>{
        let mut n=self.root;
        loop{let (_,sym,kid)=self.nodes[n];if sym!=HNODE{return Ok(sym)}n=kid+b.bit()? as usize}
    }
}
const HUFF_COEFF_MAP:[usize;22]=[13,14,11,0,1,15,16,18,2,17,3,4,19,20,5,6,21,22,7,8,9,10];
const HUFF_RUN_MAP:[usize;16]=[10,13,11,12,0,1,2,3,14,8,15,16,4,5,6,7];

// Coefficient/run/vector/mode trees (node = (jump, probability index); leaf = (-value, _)).
const PC_TREE:[(i32,usize);11]=[(4,6),(2,7),(0,0),(-1,0),(4,8),(2,9),(-2,0),(-3,0),(2,10),(-4,0),(-5,0)];
const PCR_TREE:[(i32,usize);17]=[(8,0),(4,1),(2,2),(-1,0),(-2,0),(2,3),(-3,0),(-4,0),(8,4),(4,5),(2,6),(-5,0),(-6,0),(2,7),(-7,0),(-8,0),(0,0)];
const PVA_TREE:[(i32,usize);15]=[(8,0),(4,1),(2,2),(0,0),(-1,0),(2,3),(-2,0),(-3,0),(4,4),(2,5),(-4,0),(-5,0),(2,6),(-6,0),(-7,0)];
// Macroblock types: 0 inter no-vector (previous), 1 intra, 2 inter delta, 3 near 1, 4 near 2, 5 golden no-vector,
// 6 golden delta, 7 four vectors, 8 golden near 1, 9 golden near 2.
const PMBT_TREE:[(i32,usize);19]=[(8,1),(4,2),(2,4),(0,0),(-2,0),(2,5),(-3,0),(-4,0),(4,3),(2,6),(-1,0),(-7,0),(4,7),(2,8),(-5,0),(-6,0),(2,9),(-8,0),(-9,0)];
const B6TO4:[usize;6]=[0,0,1,1,2,3];
const B2P:[usize;6]=[0,0,0,0,1,2];

#[derive(Clone,Copy,Default)] struct RefDc{frame:i8,dc:i32,not_null:bool}
#[derive(Clone,Copy,Default,PartialEq)] struct Mv{x:i32,y:i32}

#[derive(Clone)]
struct Model{
    vector_dct:[u8;2],vector_sig:[u8;2],vector_pdv:[[u8;7];2],vector_fdv:[[u8;8];2],
    stats:[[[u8;2];10];3],mb_type:[[[u8;10];10];3],
    reorder:[u8;64],index_to_pos:[u8;64],selector:[u8;64],
    dccv:[[u8;11];2],ract:[[[[u8;11];6];3];2],dcct:[[[u8;5];3];2],runv:[[u8;14];2],
}

#[derive(Clone)]
pub struct Planes{pub w:usize,pub h:usize,pub p:[Vec<u8>;3]}
impl Planes{
    fn new(w:usize,h:usize)->Self{Planes{w,h,p:[vec![0;w*h],vec![0;w/2*h/2],vec![0;w/2*h/2]]}}
    fn dims(&self,pl:usize)->(usize,usize){if pl==0{(self.w,self.h)}else{(self.w/2,self.h/2)}}
    #[inline] fn at(&self,pl:usize,x:i32,y:i32)->u8{let (w,h)=self.dims(pl);self.p[pl][(y.clamp(0,h as i32-1) as usize)*w+x.clamp(0,w as i32-1) as usize]}
    /// Top-down RGBA (BT.601, video range).
    pub fn rgba(&self,dw:usize,dh:usize)->Vec<u8>{
        let mut out=Vec::with_capacity(dw*dh*4);
        for y in 0..dh{let sy=self.h-1-y;for x in 0..dw{
            let yy=self.p[0][sy*self.w+x] as f32-16.;let u=self.p[1][(sy/2)*(self.w/2)+x/2] as f32-128.;let v=self.p[2][(sy/2)*(self.w/2)+x/2] as f32-128.;
            let c=|f:f32|f.round().clamp(0.,255.) as u8;
            out.extend_from_slice(&[c(1.164*yy+1.596*v),c(1.164*yy-0.392*u-0.813*v),c(1.164*yy+2.017*u),255]);
        }}
        out
    }
}

pub struct Decoder{
    pub w:usize,pub h:usize,pub display:(usize,usize),mbw:usize,mbh:usize,version:u8,profile:u8,
    frames:[Option<Planes>;3],model:Model,mbs:Vec<(u8,Mv)>,above:Vec<RefDc>,left:[RefDc;4],prev_dc:[[i32;3];3],
    dequant_dc:i32,dequant_ac:i32,quantizer:usize,golden:bool,mb_type:u8,cand:[Mv;2],cand_pos:usize,mv:[Mv;6],
    coeff:[[i32;64];6],selector:[usize;6],above_idx:[usize;6],pub key:bool,
    huffman:bool,dccv_h:[Huff;2],runv_h:[Huff;2],ract_h:Vec<Huff>,nb_null:[[u32;2];2],
    /// Last frame: (bool bytes consumed, first-partition size, coefficient bits consumed, coefficient bits available).
    pub consumed:(usize,usize,usize,usize),
}

fn coeff_order(m:&mut Model,version:u8){
    let mut idx=1;m.index_to_pos[0]=0;
    for i in 0..16u8{for pos in 1..64{if m.reorder[pos]==i{m.index_to_pos[idx]=pos as u8;idx+=1}}}
    for i in 0..64{let max=m.index_to_pos[..=i].iter().copied().max().unwrap_or(0);m.selector[i]=if version>6{max+1}else{63}}
}

impl Decoder{
    pub fn new()->Self{
        Decoder{w:0,h:0,display:(0,0),mbw:0,mbh:0,version:0,profile:0,frames:[None,None,None],
            model:Model{vector_dct:[0;2],vector_sig:[0;2],vector_pdv:[[0;7];2],vector_fdv:[[0;8];2],stats:[[[0;2];10];3],mb_type:[[[0;10];10];3],
                reorder:[0;64],index_to_pos:[0;64],selector:[0;64],dccv:[[0;11];2],ract:[[[[0;11];6];3];2],dcct:[[[0;5];3];2],runv:[[0;14];2]},
            mbs:vec![],above:vec![],left:[RefDc::default();4],prev_dc:[[0;3];3],dequant_dc:0,dequant_ac:0,quantizer:0,golden:false,mb_type:0,
            cand:[Mv::default();2],cand_pos:0,mv:[Mv::default();6],coeff:[[0;64];6],selector:[0;6],above_idx:[0;6],key:false,
            huffman:false,dccv_h:Default::default(),runv_h:Default::default(),ract_h:vec![],nb_null:[[0;2];2],consumed:(0,0,0,0)}
    }
    pub fn current(&self)->Option<&Planes>{self.frames[1].as_ref()}

    fn default_models(&mut self){
        let m=&mut self.model;
        m.vector_dct=[0xa2,0xa4];m.vector_sig=[0x80,0x80];
        for c in 0..3{for ty in 0..10{m.stats[c][ty][0]=t::MODE_BASELINE[c*20+10+ty];m.stats[c][ty][1]=t::MODE_BASELINE[c*20+ty];}}
        for c in 0..2{m.vector_fdv[c].copy_from_slice(&t::MV_LONG_DEFAULTS[c*8..c*8+8]);m.vector_pdv[c].copy_from_slice(&t::MV_SHORT_DEFAULTS[c*7..c*7+7]);m.runv[c].copy_from_slice(&t::RUN_DEFAULTS[c*14..c*14+14]);}
        m.reorder=t::SCAN_DEFAULT;coeff_order(m,self.version);
    }

    /// Decode one frame (`MV0K`/`MV0F` payload).  Returns the key-frame flag.
    pub fn decode(&mut self,buf:&[u8])->Result<bool,String>{
        if buf.len()<3{return Err("short VP6 frame".into())}
        let key=buf[0]&0x80==0;let quant=((buf[0]>>1)&0x3f) as usize;let separated=buf[0]&1!=0;
        self.quantizer=quant;self.dequant_dc=(t::DC_QUANT[quant] as i32)<<2;self.dequant_ac=t::AC_QUANT[quant]<<2;
        let (mut c,coeff_start);
        if key{
            let version=buf[1]>>3;let profile=(buf[1]>>1)&3;
            if version>8{return Err(format!("VP6 version {version}"))}
            if buf[1]&1!=0{return Err("interlaced VP6 is not used by these movies".into())}
            // VP6_LoadFrame: the second-partition offset follows the two header bytes when present.
            let (p,off)=if separated||profile==0{(4,u16::from_be_bytes([buf[2],buf[3]]) as usize)}else{(2,0)};
            c=Rac::new(buf.get(p..).ok_or("short key frame")?);
            let (rows,cols,drows,dcols)=(c.gets(8) as usize,c.gets(8) as usize,c.gets(8) as usize,c.gets(8) as usize);
            if rows==0||cols==0{return Err("zero macroblock dimensions".into())}
            if rows*16!=self.h||cols*16!=self.w{
                self.w=cols*16;self.h=rows*16;self.mbw=cols;self.mbh=rows;
                self.frames=[None,None,None];self.mbs=vec![(1,Mv::default());rows*cols];
            }
            self.display=(dcols*16,drows*16);self.version=version;self.profile=profile;self.golden=false;
            c.gets(2); // scaling mode
            if profile!=0{return Err("advanced-profile VP6 (filter fields) not present in the corpus".into())}
            coeff_start=off;
        }else{
            if self.w==0{return Err("inter frame before the first key frame".into())}
            let (p,off)=if separated||self.profile==0{(3,u16::from_be_bytes([buf[1],buf[2]]) as usize)}else{(1,0)};
            c=Rac::new(&buf[p..]);
            self.golden=c.prob(128);
            coeff_start=off;
        }
        self.huffman=c.prob(128);
        if self.huffman&&coeff_start==0{return Err("Huffman coefficients without a coefficient partition".into())}
        self.key=key;
        let coeff_data=if coeff_start!=0{Some(buf.get(coeff_start..).ok_or("coefficient partition offset outside frame")?)}else{None};
        // models
        if key{self.default_models();for m in self.mbs.iter_mut(){m.0=1}}
        else{self.parse_mb_type_models(&mut c);self.parse_vector_models(&mut c);self.mb_type=0;}
        self.parse_coeff_models(&mut c,key);
        if self.huffman{
            let m=&self.model;
            for pt in 0..2{self.dccv_h[pt]=Huff::build(&m.dccv[pt],&HUFF_COEFF_MAP,12);self.runv_h[pt]=Huff::build(&m.runv[pt],&HUFF_RUN_MAP,9);}
            self.ract_h=(0..36).map(|k|{let (pt,ct,g)=(k/18,(k/6)%3,k%6);Huff::build(&m.ract[pt][ct][g],&HUFF_COEFF_MAP,12)}).collect();
            self.nb_null=[[0;2];2];
        }
        let mut hb=if self.huffman{coeff_data.map(|d|Bits{d,pos:0})}else{None};
        let mut cc=if self.huffman{None}else{coeff_data.map(Rac::new)};
        // frame buffers
        let mut cur=Planes::new(self.w,self.h);
        self.prev_dc=[[0;3];3];self.prev_dc[1][0]=128;self.prev_dc[2][0]=128;
        self.above=vec![RefDc{frame:-1,dc:0,not_null:false};4*self.mbw+6];
        self.above[2*self.mbw+2].frame=0;self.above[3*self.mbw+4].frame=0;
        for row in 0..self.mbh{
            self.left=[RefDc{frame:-1,dc:0,not_null:false};4];
            self.above_idx=[1,2,1,2,2*self.mbw+3,3*self.mbw+5];
            for col in 0..self.mbw{
                self.decode_mb(&mut c,cc.as_mut(),hb.as_mut(),&mut cur,row,col,key)?;
                for y in 0..4{self.above_idx[y]+=2}for uv in 4..6{self.above_idx[uv]+=1}
            }
        }
        self.consumed=(c.pos,coeff_start,hb.as_ref().map(|b|b.pos).unwrap_or(0),coeff_data.map(|d|d.len()*8).unwrap_or(0));
        if std::env::var_os("EAGL_VP6_TRACE").is_some(){eprintln!("dccv {:?} runv {:?} ract00 {:?} reorder {:?}",self.model.dccv,self.model.runv,self.model.ract[0][0][0],&self.model.reorder[..16]);}
        if key||self.golden{self.frames[2]=Some(cur.clone())}
        self.frames[1]=Some(cur);
        Ok(key)
    }

    fn parse_mb_type_models(&mut self,c:&mut Rac){
        let m=&mut self.model;
        for ctx in 0..3{
            // VP6_DecodeModeProbs (0x802a0e14): VP6_ModeVq is [context][vector 16][mode 10][same count, weight].
            if c.prob(174){let idx=c.gets(4) as usize;for ty in 0..10{let o=ctx*320+idx*20+2*ty;m.stats[ctx][ty][0]=t::MODE_VQ[o];m.stats[ctx][ty][1]=t::MODE_VQ[o+1];}}
            if c.prob(254){
                for ty in 0..10{for i in 0..2{
                    // VP6_decodeModeDiff (0x802a0d04)
                    if c.prob(205){
                        let sign=c.bit128();
                        let delta:i32=if !c.prob(171){if c.prob(83){4}else{8}}
                            else if !c.prob(199){if c.prob(140){12}else if c.prob(125){16}else if c.prob(104){20}else{24}}
                            else{4*c.gets(7)};
                        let d=if sign{-delta}else{delta};
                        m.stats[ctx][ty][i]=(m.stats[ctx][ty][i] as i32+d).clamp(0,255) as u8;
                    }
                }}
            }
        }
        for ctx in 0..3{
            let mut p=[0i32;10];for ty in 0..10{p[ty]=100*m.stats[ctx][ty][1] as i32}
            for ty in 0..10{
                let s0=m.stats[ctx][ty][0] as i32;let s1=m.stats[ctx][ty][1] as i32;
                m.mb_type[ctx][ty][0]=(255-(255*s0)/(1+s0+s1)) as u8;
                p[ty]=0;
                let (p02,p34)=(p[0]+p[2],p[3]+p[4]);let p0234=p02+p34;let p17=p[1]+p[7];let p56=p[5]+p[6];let p89=p[8]+p[9];let p5689=p56+p89;let p156789=p17+p5689;
                let v=|a:i32,b:i32|(1+255*a/(1+b)) as u8;
                let mt=&mut m.mb_type[ctx][ty];
                mt[1]=(1+255*p0234/(1+p0234+p156789)) as u8;mt[2]=v(p02,p0234);mt[3]=v(p17,p156789);mt[4]=v(p[0],p02);mt[5]=v(p[3],p34);
                mt[6]=v(p[1],p17);mt[7]=v(p56,p5689);mt[8]=v(p[5],p56);mt[9]=v(p[8],p89);
                p[ty]=100*s1;
            }
        }
    }
    fn parse_vector_models(&mut self,c:&mut Rac){
        let m=&mut self.model;let up=|comp:usize,i:usize|t::MV_UPDATE_PROBS[comp*17+i];
        for comp in 0..2{if c.prob(up(comp,0)){m.vector_dct[comp]=c.gets_nn(7)}if c.prob(up(comp,1)){m.vector_sig[comp]=c.gets_nn(7)}}
        for comp in 0..2{for n in 0..7{if c.prob(up(comp,2+n)){m.vector_pdv[comp][n]=c.gets_nn(7)}}}
        for comp in 0..2{for n in 0..8{if c.prob(up(comp,9+n)){m.vector_fdv[comp][n]=c.gets_nn(7)}}}
    }
    fn parse_coeff_models(&mut self,c:&mut Rac,key:bool){
        let version=self.version;let m=&mut self.model;let mut def=[128u8;11];
        for pt in 0..2{for n in 0..11{if c.prob(t::DC_UPDATE_PROBS[pt*11+n]){def[n]=c.gets_nn(7);m.dccv[pt][n]=def[n]}else if key{m.dccv[pt][n]=def[n]}}}
        if c.prob(128){for pos in 1..64{if c.prob(t::SCAN_UPDATE_PROBS[pos]){m.reorder[pos]=c.gets(4) as u8}}coeff_order(m,version)}
        for g in 0..2{for n in 0..14{if c.prob(t::RUN_UPDATE_PROBS[g*14+n]){m.runv[g][n]=c.gets_nn(7)}}}
        for ct in 0..3{for pt in 0..2{for g in 0..6{for n in 0..11{
            if c.prob(t::AC_UPDATE_PROBS[((ct*2+pt)*6+g)*11+n]){def[n]=c.gets_nn(7);m.ract[pt][ct][g][n]=def[n]}else if key{m.ract[pt][ct][g][n]=def[n]}
        }}}}
        for pt in 0..2{for ctx in 0..3{for n in 0..5{
            let (a,b)=(t::DC_NODE_EQS[(n*3+ctx)*2],t::DC_NODE_EQS[(n*3+ctx)*2+1]);
            m.dcct[pt][ctx][n]=(((m.dccv[pt][n] as i32*a+128)>>8)+b).clamp(1,255) as u8;
        }}}
    }

    fn predictors(&mut self,row:usize,col:usize,frame:u8)->usize{
        let mut n=0i32;let mut v=[Mv::default();2];
        for pos in 0..12{
            let (dy,dx)=(t::NEAR_MBS[pos*2],t::NEAR_MBS[pos*2+1]);
            let (x,y)=(col as i32+dx,row as i32+dy);
            if x<0||x>=self.mbw as i32||y<0||y>=self.mbh as i32{continue}
            let (ty,mv)=self.mbs[y as usize*self.mbw+x as usize];
            if t::MODE_TO_FRAME[ty as usize] as u8!=frame{continue}
            if mv==v[0]||mv==Mv::default(){continue}
            v[n as usize]=mv;n+=1;
            if n>1{n=-1;break}
            self.cand_pos=pos;
        }
        self.cand=v;(n+1) as usize
    }
    fn vector_adjustment(&mut self,c:&mut Rac)->Mv{
        let mut v=if self.cand_pos<2{self.cand[0]}else{Mv::default()};
        let m=&self.model;
        for comp in 0..2{
            let mut delta:i32;
            if c.prob(m.vector_dct[comp]){
                delta=0;
                for &j in &[0usize,1,2,7,6,5,4]{delta|=(c.prob(m.vector_fdv[comp][j]) as i32)<<j}
                if delta&0xf0!=0{delta|=(c.prob(m.vector_fdv[comp][3]) as i32)<<3}else{delta|=8}
            }else{delta=c.tree(&PVA_TREE,&m.vector_pdv[comp])}
            if delta!=0&&c.prob(m.vector_sig[comp]){delta=-delta}
            if comp==0{v.x+=delta}else{v.y+=delta}
        }
        v
    }
    fn decode_mv(&mut self,c:&mut Rac,row:usize,col:usize)->u8{
        let ctx=self.predictors(row,col,1);
        let prev=self.mb_type as usize;
        let probs=self.model.mb_type[ctx][prev];
        self.mb_type=if c.prob(probs[0]){prev as u8}else{c.tree(&PMBT_TREE,&probs) as u8};
        let i=row*self.mbw+col;self.mbs[i].0=self.mb_type;
        let mv=match self.mb_type{
            3=>self.cand[0],4=>self.cand[1],
            8=>{self.predictors(row,col,2);self.cand[0]},9=>{self.predictors(row,col,2);self.cand[1]},
            2=>self.vector_adjustment(c),
            6=>{self.predictors(row,col,2);self.vector_adjustment(c)}
            7=>{
                let mut ty=[0;4];for b in 0..4{ty[b]=c.gets(2);if ty[b]!=0{ty[b]+=1}}
                let mut sum=Mv::default();
                for b in 0..4{
                    self.mv[b]=match ty[b]{2=>self.vector_adjustment(c),3=>self.cand[0],4=>self.cand[1],_=>Mv::default()};
                    sum.x+=self.mv[b].x;sum.y+=self.mv[b].y;
                }
                self.mbs[i].1=self.mv[3];
                let rs=|a:i32|if a>0{(a+2)>>2}else{(a+1)>>2};
                self.mv[4]=Mv{x:rs(sum.x),y:rs(sum.y)};self.mv[5]=self.mv[4];
                return self.mb_type;
            }
            _=>Mv::default(),
        };
        self.mbs[i].1=mv;for b in 0..6{self.mv[b]=mv}
        self.mb_type
    }

    fn parse_coeff(&mut self,c:&mut Rac){
        let m=&self.model;
        for b in 0..6{
            let pt=(b>3) as usize;let mut ct=1usize;
            let ctx=self.left[B6TO4[b]].not_null as usize+self.above[self.above_idx[b]].not_null as usize;
            let mut m1:&[u8]=&m.dccv[pt];let mut m2:&[u8]=&m.dcct[pt][ctx];
            let mut idx=0usize;
            loop{
                let mut run=1usize;
                if (idx>1&&ct==0)||c.prob(m2[0]){
                    let mut coeff:i32;
                    if c.prob(m2[2]){
                        if c.prob(m2[3]){
                            let tok=c.tree(&PC_TREE,m1) as usize;
                            let row=&t::TOKEN_EXTRA[(tok+5)*16..(tok+5)*16+16];
                            coeff=t::TOKEN_MIN[tok+5];let bits=u16::from_be_bytes([row[2],row[3]]) as i32;
                            for i in (0..=bits).rev(){coeff+=(c.prob(row[4+i as usize]) as i32)<<i}
                        }else if c.prob(m2[4]){coeff=3+c.prob(m1[5]) as i32}else{coeff=2}
                        ct=2;
                    }else{ct=1;coeff=1}
                    if c.bit128(){coeff=-coeff}
                    if idx!=0{coeff*=self.dequant_ac}
                    let pos=m.index_to_pos[idx] as usize;self.coeff[b][t::ZIGZAG_T[pos] as usize]=coeff;
                }else{
                    ct=0;
                    if idx>0{
                        if !c.prob(m2[1]){break}
                        let m3=&m.runv[(idx>=6) as usize];
                        run=c.tree(&PCR_TREE,m3) as usize;
                        if run==0{run=9;for i in 0..6{run+=(c.prob(m3[i+8]) as usize)<<i}}
                    }
                }
                idx+=run;
                if idx>=64{break}
                let g=t::COEFF_BANDS[idx] as usize;
                m1=&m.ract[pt][ct][g];m2=m1;
            }
            let nn=self.coeff[b][0]!=0;
            self.left[B6TO4[b]].not_null=nn;self.above[self.above_idx[b]].not_null=nn;
            self.selector[b]=m.selector[idx.min(63)] as usize;
        }
    }
    fn nb_null_count(b:&mut Bits)->Result<u32,String>{
        let mut v=b.get(2)?;
        if v==2{v+=b.get(2)?}else if v==3{let x=b.bit()?<<2;v=6+x+b.get(2+x)?}
        Ok(v)
    }
    /// Huffman token decoding (`VP6_DecodeBlock` 0x8029a898 / `VP6_ExtractTokenN`): tokens 0 (zero run), 1-10 (values,
    /// extra bits), 11 (end of block); zero-DC and first-AC end-of-block runs are counted per plane type.
    fn parse_coeff_huffman(&mut self,bits:&mut Bits)->Result<(),String>{
        for b in 0..6{
            let pt=(b>3) as usize;let mut ct=0usize;let mut idx=0usize;
            let mut hsel=usize::MAX;
            loop{
                let mut run=1usize;
                if idx<2&&self.nb_null[idx][pt]>0{
                    self.nb_null[idx][pt]-=1;
                    if idx>0{break}
                }else{
                    let tok=if hsel==usize::MAX{self.dccv_h[pt].read(bits)?}else{self.ract_h[hsel].read(bits)?};
                    if tok==0{
                        if idx>0{
                            run+=self.runv_h[(idx>=6) as usize].read(bits)? as usize;
                            if run>=9{run+=bits.get(6)? as usize}
                        }else{self.nb_null[0][pt]=Self::nb_null_count(bits)?}
                        ct=0;
                    }else if tok==11{
                        if idx==1{self.nb_null[1][pt]=Self::nb_null_count(bits)?}
                        break;
                    }else{
                        let mut v=t::TOKEN_MIN[tok as usize];
                        if tok>4{v+=bits.get(if tok<=9{tok as u32-4}else{11})? as i32}
                        ct=1+(v>1) as usize;
                        if bits.bit()?==1{v=-v}
                        if idx!=0{v*=self.dequant_ac}
                        let pos=self.model.index_to_pos[idx] as usize;self.coeff[b][t::ZIGZAG_T[pos] as usize]=v;
                    }
                }
                idx+=run;
                if idx>=64{break}
                let g=t::HUFF_BANDS[idx] as usize;
                hsel=pt*18+ct*6+g;
            }
            self.selector[b]=self.model.selector[idx.min(63)] as usize;
        }
        Ok(())
    }
    fn add_dc(&mut self,frame:u8){
        for b in 0..6{
            let (ai,li)=(self.above_idx[b],B6TO4[b]);
            let (ab,lb)=(self.above[ai],self.left[li]);
            let (mut n,mut dc)=(0,0i32);
            if lb.frame==frame as i8{dc+=lb.dc;n+=1}
            if ab.frame==frame as i8{dc+=ab.dc;n+=1}
            let pl=B2P[b];
            if n==0{dc=self.prev_dc[pl][frame as usize]}else if n==2{dc/=2}
            self.coeff[b][0]+=dc;let v=self.coeff[b][0];
            self.prev_dc[pl][frame as usize]=v;
            self.above[ai]=RefDc{frame:frame as i8,dc:v,not_null:ab.not_null};self.left[li]=RefDc{frame:frame as i8,dc:v,not_null:lb.not_null};
            self.coeff[b][0]*=self.dequant_dc;
        }
    }

    fn decode_mb(&mut self,c:&mut Rac,cc:Option<&mut Rac>,hb:Option<&mut Bits>,cur:&mut Planes,row:usize,col:usize,key:bool)->Result<(),String>{
        let ty=if key{1}else{self.decode_mv(c,row,col)};
        let frame=t::MODE_TO_FRAME[ty as usize] as u8;
        match (hb,cc){(Some(hb),_)=>self.parse_coeff_huffman(hb)?,(None,Some(cc))=>self.parse_coeff(cc),(None,None)=>self.parse_coeff(c)}
        self.add_dc(frame);
        for b in 0..6{
            let pl=B2P[b];
            let (x,y)=if b<4{(col*16+(b&1)*8,row*16+(b>>1)*8)}else{(col*8,row*8)};
            let (w,_)=cur.dims(pl);let off=y*w+x;
            let mut blk=self.coeff[b];self.coeff[b]=[0;64];
            match ty{
                1=>idct(&mut cur.p[pl][off..],w,&mut blk,true),
                0|5=>{
                    let r=self.frames[frame as usize].as_ref().ok_or("inter macroblock without a reference frame")?;
                    for j in 0..8{let (s,d)=(off+j*w,off+j*w);cur.p[pl][d..d+8].copy_from_slice(&r.p[pl][s..s+8]);}
                    add(&mut cur.p[pl][off..],w,&mut blk,self.selector[b]);
                }
                _=>{
                    let r=self.frames[frame as usize].as_ref().ok_or("inter macroblock without a reference frame")?;
                    let pred=mc(r,pl,b,self.mv[b],x as i32,y as i32);
                    for j in 0..8{cur.p[pl][off+j*w..off+j*w+8].copy_from_slice(&pred[j*8..j*8+8]);}
                    add(&mut cur.p[pl][off..],w,&mut blk,self.selector[b]);
                }
            }
        }
        Ok(())
    }
}

/// Motion-compensated 8x8 prediction (profile 0: bilinear only, no loop-filter copy).  Quarter-pel luma, eighth-pel
/// chroma; out-of-frame reads replicate the edge.
fn mc(r:&Planes,pl:usize,b:usize,mv:Mv,x:i32,y:i32)->[u8;64]{
    let div=if b<4{4}else{8};let mask=div-1;
    let (dx,dy)=(mv.x/div,mv.y/div);
    // 12x12 source window at (x+dx-2, y+dy-2)
    let mut src=[0u8;144];
    for j in 0..12{for i in 0..12{src[j*12+i]=r.at(pl,x+dx-2+i as i32,y+dy-2+j as i32)}}
    let base=2+2*12;let mut off1=base as i32;let mut ov=0i32;
    if mv.x&mask!=0{ov+=if mv.x>0{1}else{-1}}
    if mv.y&mask!=0{ov+=if mv.y>0{12}else{-12}}
    let mut out=[0u8;64];
    if ov==0{for j in 0..8{for i in 0..8{out[j*8+i]=src[base+j*12+i]}}return out}
    let (mut x8,mut y8)=(mv.x&mask,mv.y&mask);if b<4{x8*=2;y8*=2}
    let off2=off1+ov;
    if off2<off1{off1=off2}
    let bil=|dst:&mut [u8],s:&[u8],so:usize,ss:usize,rows:usize,ds:usize,x8:i32,y8:i32|{
        let (a,bb,cc,d)=((8-x8)*(8-y8),x8*(8-y8),(8-x8)*y8,x8*y8);
        for j in 0..rows{for i in 0..8{
            let p=|k:usize|s[so+j*ss+i+k] as i32;
            dst[j*ds+i]=if d!=0{((a*p(0)+bb*p(1)+cc*p(ss)+d*p(ss+1)+32)>>6) as u8}
                else if bb+cc!=0{let step=if cc!=0{ss}else{1};((a*p(0)+(bb+cc)*p(step)+32)>>6) as u8}
                else{((a*p(0)+32)>>6) as u8};
        }}
    };
    if x8==0||y8==0{bil(&mut out,&src,off1 as usize,12,8,8,x8,y8)}
    else{
        let o=(off1+((mv.x^mv.y)>>31)) as usize;
        let mut tmp=[0u8;9*8];bil(&mut tmp,&src,o,12,9,8,x8,0);bil(&mut out,&tmp,0,8,8,8,0,y8);
    }
    out
}

const C1:i32=64277;const C2:i32=60547;const C3:i32=54491;const C4:i32=46341;const C5:i32=36410;const C6:i32=25080;const C7:i32=12785;
#[inline] fn mm(a:i32,b:i32)->i32{((a as u32).wrapping_mul(b as u32) as i32)>>16}
fn clip(v:i32)->u8{v.clamp(0,255) as u8}
/// VP3/VP6 integer inverse DCT (`put` writes, otherwise adds); `input` is in transposed raster order.
fn idct(dst:&mut [u8],stride:usize,input:&mut [i32;64],put:bool){
    for i in 0..8{
        let c=|k:usize|input[k*8+i];
        if (0..8).any(|k|c(k)!=0){
            let a=mm(C1,c(1))+mm(C7,c(7));let b=mm(C7,c(1))-mm(C1,c(7));let cc=mm(C3,c(3))+mm(C5,c(5));let d=mm(C3,c(5))-mm(C5,c(3));
            let ad=mm(C4,a-cc);let bd=mm(C4,b-d);let cd=a+cc;let dd=b+d;
            let e=mm(C4,c(0)+c(4));let f=mm(C4,c(0)-c(4));let g=mm(C2,c(2))+mm(C6,c(6));let h=mm(C6,c(2))-mm(C2,c(6));
            let (ed,gd,add,bdd,fd,hd)=(e-g,e+g,f+ad,bd-h,f-ad,bd+h);
            let o=[gd+cd,add+hd,add-hd,ed+dd,ed-dd,fd+bdd,fd-bdd,gd-cd];
            for k in 0..8{input[k*8+i]=o[k]}
        }
    }
    for i in 0..8{
        let r=&input[i*8..i*8+8];
        if r[1..].iter().any(|&v|v!=0){
            let a=mm(C1,r[1])+mm(C7,r[7]);let b=mm(C7,r[1])-mm(C1,r[7]);let cc=mm(C3,r[3])+mm(C5,r[5]);let d=mm(C3,r[5])-mm(C5,r[3]);
            let ad=mm(C4,a-cc);let bd=mm(C4,b-d);let cd=a+cc;let dd=b+d;
            let mut e=mm(C4,r[0]+r[4])+8;let mut f=mm(C4,r[0]-r[4])+8;
            if put{e+=16*128;f+=16*128}
            let g=mm(C2,r[2])+mm(C6,r[6]);let h=mm(C6,r[2])-mm(C2,r[6]);
            let (ed,gd,add,bdd,fd,hd)=(e-g,e+g,f+ad,bd-h,f-ad,bd+h);
            let o=[gd+cd,add+hd,add-hd,ed+dd,ed-dd,fd+bdd,fd-bdd,gd-cd];
            for k in 0..8{let p=&mut dst[k*stride+i];*p=if put{clip(o[k]>>4)}else{clip(*p as i32+(o[k]>>4))}}
        }else if put{
            let v=clip(128+((C4*r[0]+(8<<16))>>20));for k in 0..8{dst[k*stride+i]=v}
        }else if r[0]!=0{
            let v=(C4*r[0]+(8<<16))>>20;for k in 0..8{let p=&mut dst[k*stride+i];*p=clip(*p as i32+v)}
        }
    }
    *input=[0;64];
}
fn add(dst:&mut [u8],stride:usize,blk:&mut [i32;64],selector:usize){
    if selector>1{idct(dst,stride,blk,false)}
    else{let dc=(blk[0]+15)>>5;for j in 0..8{for i in 0..8{let p=&mut dst[j*stride+i];*p=clip(*p as i32+dc)}}*blk=[0;64]}
}

// ---------------------------------------------------------------------------------------------------------------
// EA container

pub struct Movie{pub width:usize,pub height:usize,pub frames:u32,pub rate:(u32,u32),pub chunks:Vec<([u8;4],usize,usize)>}
/// `MVhd` header (codec word, u16 width/height, frame count, largest frame, rate denominator/numerator; little-endian)
/// followed by chunks: `MV0K` key frames, `MV0F` inter frames, `SCHl`/`SCCl`/`SCDl`/`SCEl` interleaved EA audio.
pub fn movie(d:&[u8])->Result<Movie,String>{
    if d.get(..4)!=Some(b"MVhd"){return Err("not an EA MVhd movie".into())}
    let le=|o:usize|->Result<u32,String>{d.get(o..o+4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).ok_or_else(||format!("read past end at {o:#x}"))};
    let le16=|o:usize|->Result<usize,String>{d.get(o..o+2).map(|b|u16::from_le_bytes([b[0],b[1]]) as usize).ok_or("short header".to_string())};
    let mut chunks=vec![];let mut p=0;
    while p+8<=d.len(){
        let tag:[u8;4]=d[p..p+4].try_into().unwrap();let n=le(p+4)? as usize;
        if n<8||p+n>d.len(){return Err(format!("chunk {} at {p:#x} size {n:#x} outside file",String::from_utf8_lossy(&tag)))}
        chunks.push((tag,p,n));p+=n;
    }
    if p!=d.len(){return Err(format!("{} trailing bytes after the last chunk",d.len()-p))}
    Ok(Movie{width:le16(0xc)?,height:le16(0xe)?,frames:le(0x10)?,rate:(le(0x18)?,le(0x1c)?),chunks})
}
