"""Generate/check a function-addressed comparison index from the pinned ELF.

This exports disassembly, not decompiled C++. Fixture counts are direct entry
cases, not instruction/branch coverage or proof of unhooked engine services.
"""
import hashlib
import json
import re
import sys
from collections import Counter
from pathlib import Path

import re_functions as rf
import animation_playback_oracle as oracle

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / '_bevy/docs/evidence/animation_playback'
ELF = ROOT / 'Remaster/reference/playgroundz.elf'
SHA = '5cef3efc7005fb71fed0a75e60ee240ee6ac4243b00dd3296e6e53ca269a3e2c'
FUNCTIONS = [
    ('SetNextAnim', 0x803c8318, 'select', 'select'),
    ('Update', 0x803c851c, 'update', 'update'),
    ('ProcessAnimEvents', 0x803c89a4, 'events', 'events'),
    ('SetNextAnimState', 0x803c8b78, 'set_next', 'set_next'),
    ('SetStateTime', 0x803c8c84, 'set_state_time', 'time'),
    ('GetStateTime', 0x803c8cd4, 'state_time', 'time'),
]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def generate():
    assert digest(ELF.read_bytes()) == SHA, 'wrong source executable'
    exe = rf.load()
    rust_path = '_bevy/src/animation_playback.rs'
    rust = (ROOT / rust_path).read_text()
    fixture_path = '_bevy/tests/data/animation_playback_golden.json'
    fixture = json.loads((ROOT / fixture_path).read_text())
    assert fixture['elf_sha256'] == SHA
    counts = Counter(case['operation'] for case in fixture['cases'])
    outputs = {}
    rows = []
    for label, address, method, operation in FUNCTIONS:
        matches = [(name, s) for name, s in exe.symbols.items()
                   if s['value'] == address and s['size']]
        assert len(matches) == 1, (label, matches)
        symbol, info = matches[0]
        assert label + '__' in symbol, symbol
        match = re.search(r'    pub fn ' + method + r'\(', rust)
        assert match is not None, method
        line = rust[:match.start()].count('\n') + 1
        filename = f'{address:08x}-{label}.txt'
        outputs[filename] = rf.annotate(exe, symbol) + '\n'
        rows.append(dict(name=label, symbol=symbol, address=f'0x{address:08x}',
                         size_bytes=info['size'],
                         instruction_bytes_sha256=digest(exe.read(address, info['size'])),
                         disassembly=filename, rust=dict(path=rust_path, method=method, line=line),
                         status='ported + finite differential comparison',
                         oracle_operation=operation, direct_fixture_cases=counts[operation],
                         fixture_case_ids=[i for i, c in enumerate(fixture['cases']) if c['operation'] == operation],
                         comparison='projected state float bits and ordered service effects'))
    sources = ['_bevy/src/animation_playback.rs', '_bevy/src/animation_playback_tests.rs',
               '_bevy/tools/animation_playback_oracle.py', '_bevy/tools/ppc_emu2.py',
               '_bevy/tools/animation_graph_oracle.py', fixture_path,
               '_bevy/tests/data/animation_graph_golden.json']
    sources += sorted({str(Path(m.__file__).resolve().relative_to(ROOT)).replace('\\', '/')
                       for m in tuple(sys.modules.values())
                       if getattr(m, '__file__', None)
                       and Path(m.__file__).resolve().is_relative_to(ROOT / '_bevy/tools')})
    graph_fixture = json.loads((ROOT / '_bevy/tests/data/animation_graph_golden.json').read_text())
    host = oracle.PlaybackEmu(exe, graph_fixture)
    assert not any(address in host.hooks for _, address, _, _ in FUNCTIONS)
    manifest = dict(elf_path='Remaster/reference/playgroundz.elf', elf_sha256=SHA,
                    functions=rows, fixture_cases_total=len(fixture['cases']),
                    source_sha256={p: digest((ROOT / p).read_bytes()) for p in sources},
                    installed_hooks=[dict(address=f'0x{a:08x}', symbol=exe.addresses.get(a, 'synthetic service'))
                                     for a in sorted(host.hooks)],
                    hook_inventory_scope='installed hooks, including inherited hooks; not an executed-callee ledger',
                    native_source='symbol-bearing compiled PowerPC executable',
                    decompiled_cpp='not supplied or generated by this evidence bundle',
                    scope='finite-input differential comparison through a local PowerPC interpreter; engine services hooked',
                    test='_bevy/src/animation_playback_tests.rs::original_animation_state_calls')
    outputs['index.json'] = json.dumps(manifest, indent=2) + '\n'
    table = '\n'.join(f"| {r['address']} `{r['name']}` | [{r['disassembly']}]({r['disassembly']}) | "
                      f"[`{r['rust']['method']}`](../../../src/animation_playback.rs#L{r['rust']['line']}) | "
                      f"`{r['oracle_operation']}` / {r['direct_fixture_cases']} |" for r in rows)
    outputs['README.md'] = '''# Function comparison index: AnimationState

Generated from the pinned compiled executable. Each assembly listing includes
the original instruction words, address, symbol and resolved call targets.
`index.json` pins each function's machine bytes and the comparison source files
by SHA-256. Rust is organized by subsystem, not original C++ translation unit.

| Compiled function | Original instructions | Rust implementation | Oracle entry / cases |
|---|---|---|---|
''' + table + '''

The 256 cases are shared across these entries; the two time accessors run in the
same cases. Nested state/event calls also execute, but these counts do not measure
branch or instruction coverage. The listings are disassembly, not decompiled C++.

Follow a comparison through [oracle inputs and original-code calls](../../../tools/animation_playback_oracle.py),
[recorded native results](../../../tests/data/animation_playback_golden.json), and
[Rust comparisons](../../../src/animation_playback_tests.rs). Native fixture
regeneration reads the original ELF; the Rust test consumes those fixtures and
compares state float bits and ordered service requests.

Engine allocation, lengths, RNG, skeleton/pose/mask operations, marker matrices
and handler bodies are supplied boundaries. This does not verify rendered poses,
console execution, allocator defaults, arbitrary floating-point inputs or full
gameplay. Read [scope and recovered behavior](../../ANIMATION_PLAYBACK.md).

From the repository root:

```powershell
py -3.14 _bevy/tools/animation_playback_evidence.py --check
py -3.14 _bevy/tools/animation_playback_oracle.py --check
cargo test --manifest-path _bevy/Cargo.toml --release --offline --locked animation_playback
```

The first command validates listings and source hashes. The second regenerates
native results for comparison with the checked-in fixture. The third executes
the compiled Rust implementation. This index currently covers these six
functions; it is not a repository-wide inventory of ported functions.
'''
    return outputs


if __name__ == '__main__':
    outputs = generate()
    if '--check' in sys.argv:
        for name, content in outputs.items():
            assert (OUT / name).read_text() == content, f'stale evidence: {name}'
    else:
        OUT.mkdir(parents=True, exist_ok=True)
        for name, content in outputs.items():
            (OUT / name).write_text(content, encoding='utf-8')
    print(f'Verified {len(FUNCTIONS)} function mappings and {len(outputs)} evidence files')
