"""Generate src/recovered.rs and docs/recovered-constants.json from playgroundz.elf.

Every value is read from the executable's own named globals (or a CharacterState
constructor immediate, see CTOR_FIELDS).  Nothing here is hand-typed: re-run after
changing the ELF.  `--check` verifies the checked-in output is current (used by prove.py).
"""
import sys,struct,json,hashlib
from pathlib import Path
HERE=Path(__file__).resolve().parent;BEVY=HERE.parent
sys.path[:0]=[str(HERE)]
import re_functions as rf

# (rust name, ELF symbol, kind, what the game uses it for)
GLOBALS=[
 ('TURN_RATE','gTurnRate','f32','LocalCharacterControl::Update turn step (analog, normal)'),
 ('TURN_RATE_FAST','gTurnRateFast','f32','LocalCharacterControl::Update turn step (analog, large heading error)'),
 ('TURN_RATE_DIGITAL','gTurnRateDigital','f32','LocalCharacterControl::Update turn step (digital/dpad input)'),
 ('STOP_TIME_BEFORE_ABSOLUTE_MOVEMENT_MS','gLocalCharacterControlStopTimeBeforeAbsoluteMovement','i32','idle time (ms) before movement becomes camera-absolute again'),
 ('DIGITAL_TRANSITION_TIME_MS','gDigitalTransitionTime','i32','dpad-to-analog smoothing ramp time (ms)'),
 ('ORBIT_CAMERA_DISTANCE','gOrbitCameraDistance','f32','orbit camera distance'),
 ('ORBIT_CAMERA_HEIGHT','gOrbitCameraHeight','f32','orbit camera height'),
 ('HINGE_CAMERA_DISTANCE','gHingeCameraDistance','f32','hinge camera distance'),
 ('HINGE_CAMERA_DISTANCE_FAR','gHingeCameraDistanceFar','f32','hinge camera far distance'),
 ('FRAME_CAMERA_DISTANCE','gFrameCameraDistance','f32','frame camera distance'),
 ('FRAME_CAMERA_HEIGHT','gFrameCameraHeight','f32','frame camera height'),
 ('CAMERA_SPEED_CAP','gCameraSpeedCap','f32','camera speed cap'),
 ('CAMERA_TRANSITION_SPEED','gTransitionSpeed','f32','camera transition speed'),
]
# CharacterState::CharacterState() stores these float immediates (offset -> label).
CTOR='__ct__14CharacterStateFv'
CTOR_FIELDS=[(0x10,'STATE_FIELD_10'),(0x14,'STATE_FIELD_14'),(0x18,'STATE_MAX_SPEED'),(0x1c,'STATE_FIELD_1C'),(0x20,'STATE_FIELD_20'),(0x24,'STATE_FIELD_24')]
# Constants the deadzone/rest of Update read from .sdata2 (address printed by re_functions).
SDATA2=[('STICK_DEAD_ZONE',0x80605834,'f32','LocalCharacterControl::Update: |axis| must exceed this (0x802ef1fc)'),
        ('PI',0x8060583c,'f32','pi used by Update'),('DEG_PER_PI',0x80605840,'f32','180.0 used to convert camera yaw'),
        ('ANIM_SPEED_EPSILON',0x806057e4,'f32','CharacterMovement::Update: walk if speed <= CharacterState+0x1c + this, else run (0x802ed83c-0x802ed848)'),
        ('ARRIVAL_SLOWDOWN_START',0x806057ec,'f32','CharacterMovement::Update waypoint following: distance at which slow-down starts (0x802ed9d4)'),
        ('ARRIVAL_SLOWDOWN_RANGE',0x806057f0,'f32','CharacterMovement::Update waypoint following: slow-down ramp length (0x802ed9d8)'),
        ('WAYPOINT_TURN_PER_MS_SLOW',0x806057f4,'f32','CharacterMovement::Update: turn blend per millisecond (0x802eda4c)'),
        ('WAYPOINT_TURN_PER_MS_FAST',0x806057f8,'f32','CharacterMovement::Update: turn blend per millisecond (0x802eda5c)'),]

def ctor_floats(e):
    """Decode `lfs fN,off(r2)` then `stfs fN,field(r3)` pairs in the constructor."""
    s=e.symbols[CTOR];data=e.read(s['value'],s['size']);base=e.symbols['_SDA2_BASE_']['value']
    regs={};out={}
    for off in range(0,s['size'],4):
        w=int.from_bytes(data[off:off+4],'big');op=w>>26
        if op==48: # lfs
            fr=(w>>21)&31;ra=(w>>16)&31;d=w&0xffff;d-=0x10000 if d&0x8000 else 0
            if ra==2:regs[fr]=struct.unpack('>f',e.read(base+d,4))[0]
        elif op==52: # stfs
            fr=(w>>21)&31;ra=(w>>16)&31;d=w&0xffff
            if ra==31 and fr in regs:out[d]=regs[fr]
    return out

def build():
    e=rf.load();items=[];
    for rust,sym,kind,doc in GLOBALS:
        s=e.symbols[sym];b=e.read(s['value'],4)
        v=struct.unpack('>f' if kind=='f32' else '>i',b)[0]
        items.append(dict(rust=rust,kind=kind,value=v,symbol=sym,address=s['value'],doc=doc))
    cf=ctor_floats(e);c=e.symbols[CTOR]
    for off,rust in CTOR_FIELDS:
        items.append(dict(rust=rust,kind='f32',value=cf[off],symbol=f'{CTOR}+field {off:#x}',address=c['value'],doc=f'CharacterState default at +{off:#x}'))
    for rust,addr,kind,doc in SDATA2:
        v=struct.unpack('>f',e.read(addr,4))[0]
        items.append(dict(rust=rust,kind=kind,value=v,symbol=f'.sdata2@{addr:#x}',address=addr,doc=doc))
    return items,hashlib.sha256(e.path.read_bytes()).hexdigest()

def rust(items,sha):
    out=['//! GENERATED by tools/extract_constants.py from playgroundz.elf - do not edit.',
         f'//! ELF SHA-256: {sha}','#![allow(dead_code)]','']
    for i in items:
        t='f32' if i['kind']=='f32' else 'i32'
        v=repr(i['value']) if t=='f32' else str(i['value'])
        if t=='f32' and 'e' not in v and '.' not in v:v+='.0'
        out.append(f"/// {i['doc']} - `{i['symbol']}` @ {i['address']:#010x}")
        out.append(f"pub const {i['rust']}: {t} = {v};")
    out.append(f'pub const ELF_SHA256: &str = "{sha}";')
    return '\n'.join(out)+'\n'

if __name__=='__main__':
    items,sha=build();text=rust(items,sha)
    tgt=BEVY/'src/recovered.rs'
    if '--check' in sys.argv:
        ok=tgt.exists() and tgt.read_text(encoding='utf-8')==text;print('recovered.rs',"up to date" if ok else "STALE");sys.exit(0 if ok else 1)
    tgt.write_text(text,newline='\n')
    (BEVY/'docs/recovered-constants.json').write_text(json.dumps(dict(elf_sha256=sha,constants=items),indent=1),encoding='utf-8')
    print('wrote',tgt,len(items),'constants')
