"""Generate src/mp3_tables.rs from playgroundz.elf: the executable's own MPEG layer-3 tables.

The game's EALayer3 decoder (Snd::CEALayer3 / CMpegLayer3Base, 0x80280888..0x80286758) keeps its Huffman trees, scale
factor band tables, pretab, slen/nr_of_sfb tables and the synthesis window in read-only data.  Everything here is read from
those symbols; `--check` verifies the checked-in output is current (used by prove.py).

Reconstruction notes (verified below, the script aborts if a check fails):
  * `sHuffTables` (32 pointers) -> `gHuffTableN` trees of big-endian i16: v >= 0 is a leaf ((x << 4) | y); v < 0 means
    "on a 1 bit advance |v| entries", read from `DecodeHuffman` 0x80282628.
  * `sfBandIndex` rows (9 sample rates x 30 u16): 23 long-block boundaries followed by 7 u16 that pack the short-block
    boundaries: [b0, (b1,b2), (b3,b4), ...] as high/low bytes.
  * `decwin` is the polyphase synthesis window in the layout of mpg123's `make_decode_tables` (values = intwinbase/2 with
    alternating sign); the 257-entry prototype is recovered from both halves of that layout and must agree.
"""
import sys,struct,hashlib
from pathlib import Path
HERE=Path(__file__).resolve().parent;BEVY=HERE.parent
sys.path[:0]=[str(HERE)]
import re_functions as rf

def build():
    e=rf.load();S=e.symbols
    rd=lambda n,size=None:e.read(S[n]['value'],size or S[n]['size'])
    addr2name={s['value']:n for n,s in S.items() if n.startswith('gHuffTable') and 'Count' not in n}
    ptrs=struct.unpack('>32I',rd('sHuffTables__Q23Snd15CMpegLayer3Base'))
    trees={};table_ref=[]
    for i,p in enumerate(ptrs):
        n=addr2name.get(p)
        if n is None:table_ref.append(None);continue
        key=n.split('__')[0]
        if key not in trees:
            raw=rd(n);trees[key]=list(struct.unpack('>%dh'%(len(raw)//2),raw))
        table_ref.append(key)
    linbits=list(rd('sHuffTableLinearBits__Q23Snd15CMpegLayer3Base'))
    counts=[]
    cs=rd('sHuffCountTables__Q23Snd15CMpegLayer3Base')
    for i in range(2):
        p,=struct.unpack('>I',cs[i*8:i*8+4]);shift,=struct.unpack('>H',cs[i*8+6:i*8+8])
        n=addr2name and next(n for n,s in S.items() if s['value']==p and 'Count' in n)
        counts.append((list(rd(n)),shift))
    slen=list(rd('slen__Q23Snd15CMpegLayer3Base'))
    numsfb=list(rd('sNumSfbBlock__Q23Snd9CMpegBase'))
    pretab=list(rd('pretab__3Snd'))
    rates=list(struct.unpack('>9H',rd('sSampleRateTable__Q23Snd9CMpegBase')))
    sfb=struct.unpack('>270H',rd('sfBandIndex__Q23Snd15CMpegLayer3Base'))
    long_=[];short=[]
    for r in range(9):
        row=sfb[r*30:(r+1)*30];long_.append(list(row[:23]))
        packed=row[23:];sh=[0,packed[0]]
        for v in packed[1:]:sh+=[v>>8,v&255]
        assert len(sh)==14 and sh==sorted(sh),(r,sh)
        short.append(sh)
    # synthesis window prototype from decwin
    dw=struct.unpack('>544f',rd('decwin__3Snd'))
    idx=0;pos=[]
    for i in range(512):
        if idx<512+16:pos.append((i,idx))
        if i%32==31:idx-=1023
        idx+=32
    inter={}
    for i,ix in pos:
        j=i if i<=256 else 512-i
        # decwin = -intwin * 0.5 * (-1)^(i // 64)
        v=-2*dw[ix]*(-1 if (i//64)%2 else 1)
        v2=-2*dw[ix+16]*(-1 if (i//64)%2 else 1)
        assert abs(v-v2)<1e-6,('copies differ',i,ix)
        if j in inter:assert abs(inter[j]-v)<1e-6,('halves disagree',j,inter[j],v)
        inter[j]=v
    assert sorted(inter)==list(range(257)),('window prototype incomplete',[j for j in range(257) if j not in inter][:10])
    intwin=[int(round(inter[j])) for j in range(257)]
    assert all(abs(inter[j]-intwin[j])<1e-6 for j in range(257)) and intwin[256]==75038 and intwin[1]==-1
    xaf=list(struct.unpack('>8f',rd('xafilterf__3Snd')));xat=list(struct.unpack('>256f',rd('xatablef__3Snd')))
    utk_coeff=list(struct.unpack('>64f',rd('coeff_table__3Snd')));utk_index=list(rd('index_table__3Snd'))
    dt=rd('decode_table__3Snd');utk_decode=[struct.unpack('>iif',dt[i*12:i*12+12]) for i in range(len(dt)//12)]
    return dict(utk_coeff=utk_coeff,utk_index=utk_index,utk_decode=utk_decode,xaf=xaf,xat=xat,trees=trees,table_ref=table_ref,linbits=linbits,counts=counts,slen=slen,numsfb=numsfb,pretab=pretab,rates=rates,long=long_,short=short,intwin=intwin),hashlib.sha256(Path(rf.__file__).parent.joinpath('../../Remaster/reference/playgroundz.elf').resolve().read_bytes()).hexdigest()

def arr(name,ty,vals,per=16):
    body=',\n    '.join(', '.join(str(v) for v in vals[i:i+per]) for i in range(0,len(vals),per))
    return f'pub const {name}: [{ty}; {len(vals)}] = [\n    {body}\n];\n'

def render(t,sha):
    out=['//! GENERATED by tools/extract_audio_tables.py from playgroundz.elf - do not edit.',f'//! ELF SHA-256: {sha}','//! MPEG layer-3 tables of the game\'s own decoder (Snd::CEALayer3 / CMpegLayer3Base).','#![allow(dead_code)]','']
    keys=sorted(t['trees'],key=lambda k:int(k[len('gHuffTable'):]))
    for k in keys:out.append(arr('HUFF_'+k[len('gHuffTable'):],'i16',t['trees'][k],16))
    out.append('/// `sHuffTables`: big-value table index -> tree (None = table not used / zero region).')
    refs=', '.join('None' if r is None else f'Some(&HUFF_{r[len("gHuffTable"):]})' for r in t['table_ref'])
    out.append(f'pub const HUFF_TABLES: [Option<&[i16]>; 32] = [{refs}];')
    out.append(arr('HUFF_LINBITS','u8',t['linbits'],32))
    for i,(tab,shift) in enumerate(t['counts']):
        out.append(arr(f'COUNT1_TABLE_{i}','u8',tab,16));out.append(f'pub const COUNT1_SHIFT_{i}: u32 = {shift};\n')
    out.append(arr('SLEN','u8',t['slen'],16));out.append('/// `sNumSfbBlock`: LSF nr_of_sfb partitions (3 x 6 x 4).')
    out.append(arr('NUM_SFB_BLOCK','u8',t['numsfb'],12));out.append(arr('PRETAB','u8',t['pretab'],22))
    out.append(arr('SAMPLE_RATES','u16',t['rates'],9))
    out.append('/// Long-block scale factor band boundaries per sample-rate index (0..8).')
    out.append('pub const SFB_LONG: [[u16; 23]; 9] = ['+', '.join('['+', '.join(map(str,r))+']' for r in t['long'])+'];')
    out.append('/// Short-block boundaries (per window) per sample-rate index.')
    out.append('pub const SFB_SHORT: [[u16; 14]; 9] = ['+', '.join('['+', '.join(map(str,r))+']' for r in t['short'])+'];')
    def farr(name,vals,per):
        body=(','+chr(10)+'    ').join(', '.join(repr(v) for v in vals[k:k+per]) for k in range(0,len(vals),per))
        return 'pub const '+name+': [f32; '+str(len(vals))+'] = ['+chr(10)+'    '+body+chr(10)+'];'+chr(10)
    out.append('/// EA-XA (`decodexac` 0x80280dfc): predictor coefficients (`xafilterf`) and per-shift nibble table (`xatablef`, 16 x 16).')
    out.append(farr('XA_FILTER',t['xaf'],4));out.append(farr('XA_TABLE',t['xat'],8))
    out.append('/// EA MicroTalk / UTK speech codec (`decodemut` 0x80287208, `readsamples` 0x8028692c): reflection-coefficient table, pulse-code state table (2 states x 256) and entry table (next state, bits, value).')
    out.append(farr('UTK_COEFF',t['utk_coeff'],8));out.append(arr('UTK_INDEX','u8',t['utk_index'],32))
    out.append('pub const UTK_DECODE: [(i32, i32, f32); '+str(len(t['utk_decode']))+'] = ['+', '.join('('+str(a)+', '+str(b)+', '+repr(c)+')' for a,b,c in t['utk_decode'])+'];')
    out.append(arr('SYNTH_WINDOW_INT','i32',t['intwin'],11))
    return '\n'.join(out)+'\n'

if __name__=='__main__':
    t,sha=build();text=render(t,sha);tgt=BEVY/'src'/'mp3_tables.rs'
    if '--check' in sys.argv:
        ok=tgt.exists() and tgt.read_text(encoding='utf-8')==text;print('mp3_tables.rs','up to date' if ok else 'STALE');sys.exit(0 if ok else 1)
    tgt.write_text(text,newline='\n');print('wrote',tgt,len(text)//1024,'KiB;',len(t['trees']),'distinct Huffman trees')
