"""Generate src/vp6_tables.rs from playgroundz.elf: the constant tables of the On2 VP6 decoder linked into the game
(VP6_* symbols, 0x8043b000-0x8043d5b0).  Every table is copied from the executable; layouts are documented next to
each constant.  Usage:  py -3.14 tools/extract_vp6_tables.py
"""
import sys,struct
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]/'Remaster'
sys.path[:0]=[str(ROOT/'src'),str(ROOT/'research/deps'),str(ROOT/'research')]
from elf_trace import Executable
e=Executable()
def raw(n):s=e.symbols[n];return e.read(s['value'],s['size'])
def u8(n):return list(raw(n))
def i32(n):b=raw(n);return list(struct.unpack('>%di'%(len(b)//4),b))
def i16(n):b=raw(n);return list(struct.unpack('>%dh'%(len(b)//2),b))
out=['//! Generated by tools/extract_vp6_tables.py from playgroundz.elf (symbol names given per table). Do not edit.','']
def emit(name,ty,vals,doc):out.append(f'/// {doc}');out.append(f'pub const {name}:[{ty};{len(vals)}]=[{",".join(map(str,vals))}];')
emit('DC_UPDATE_PROBS','u8',u8('VP6_DcUpdateProbs'),'`VP6_DcUpdateProbs` [plane type 2][node 11]')
emit('SCAN_UPDATE_PROBS','u8',u8('ScanBandUpdateProbs'),'`ScanBandUpdateProbs` [64]')
emit('RUN_UPDATE_PROBS','u8',u8('ZrlUpdateProbs'),'`ZrlUpdateProbs` [group 2][node 14]')
emit('RUN_DEFAULTS','u8',u8('ZeroRunProbDefaults'),'`ZeroRunProbDefaults` [group 2][node 14]')
emit('AC_UPDATE_PROBS','u8',u8('VP6_AcUpdateProbs'),'`VP6_AcUpdateProbs` [code type 3][plane type 2][band 6][node 11]')
emit('DC_NODE_EQS','i32',i32('VP6_DcNodeEqs'),'`VP6_DcNodeEqs` [node 5][context 3][scale, offset]')
emit('MODE_BASELINE','u8',u8('VP6_BaselineXmittedProbs')[:60],'`VP6_BaselineXmittedProbs` [context 3][2][mode 10]; row 0 = "different" counts, row 1 = "same" counts')
emit('MODE_VQ','u8',u8('VP6_ModeVq'),'`VP6_ModeVq` [context 3][vector 16][mode 10][same count, weight]')
emit('MV_UPDATE_PROBS','u8',u8('VP6_MvUpdateProbs'),'`VP6_MvUpdateProbs` [component 2][is-long, sign, short 7, long 8]')
emit('MV_SHORT_DEFAULTS','u8',u8('DefaultMvShortProbs'),'`DefaultMvShortProbs` [component 2][7]')
emit('MV_LONG_DEFAULTS','u8',u8('DefaultMvLongProbs'),'`DefaultMvLongProbs` [component 2][8]')
emit('MODE_TO_FRAME','i32',i32('VP6_Mode2Frame')[:10],'`VP6_Mode2Frame` [mode 10]: 0 current (intra), 1 previous, 2 golden')
emit('SCAN_DEFAULT','u8',u8('DefaultNonInterlacedScanBands'),'`DefaultNonInterlacedScanBands` [64]')
emit('COEFF_BANDS','i32',i32('VP6_CoeffToBand')[:64],'`VP6_CoeffToBand` [coefficient index 64] (entry 0, the DC, is -1 and unused)')
emit('HUFF_BANDS','i32',i32('VP6_CoeffToHuffBand')[:64],'`VP6_CoeffToHuffBand` [coefficient index 64] (bands capped at 3 for the Huffman tables)')
emit('TOKEN_MIN','i32',i32('VP6_HuffTokenMinVal')[:11],'`VP6_HuffTokenMinVal` [token 11]')
emit('TOKEN_EXTRA','u8',u8('VP6_TokenExtraBits2'),'`VP6_TokenExtraBits2` [token 12][u16 min, u16 extra bits - 1, probabilities 12]')
emit('DC_QUANT','i16',i16('VP6_DcQuant'),'`VP6_DcQuant` [quantizer 64]')
emit('AC_QUANT','i32',i32('VP6_QThreshTable'),'`VP6_QThreshTable` [quantizer 64] (AC dequantisation)')
emit('BILINEAR','i32',i32('BilinearFilters'),'`BilinearFilters` [phase 8][2]')
emit('BICUBIC','i32',i32('BicubicFilters'),'`BicubicFilters` [phase 8][4]')
emit('LOOP_FILTER_LIMITS','i32',i32('LoopFilterLimitValuesVp6'),'`LoopFilterLimitValuesVp6` [quantizer 64]')
emit('NEAR_MBS','i32',i32('NearMacroBlocks'),'`NearMacroBlocks` [12][row offset, column offset]')
emit('ZIGZAG_T','i32',i32('zigzag'),'`zigzag` [64]: scan position -> transposed raster index (the IDCT input order)')
dst=Path(__file__).resolve().parents[1]/'src'/'vp6_tables.rs';dst.write_text('\n'.join(out)+'\n')
print('wrote',dst)
